### ISSUE TITLE
Allow GPG-signed-only enforcement

### ISSUE THREAD

**Issue by Grimwind** [iver-wharf/iver-wharf.github.io#36]
Enforcing GPG signed Git commits is a great security feature for anything that deals with Git repos.

Suggested implementation:
- When enabled, reject builds on commits that are unsigned or unverified.

- Users provide Wharf with a list of public keys that it has in its own storage that cmd project then uses with a basic `git verify-commit HEAD` call, preferably with a simple `--verify-commit` flag or something to the cmd command.

  - To extend later (in a different WO): Wharf refreshes its DB of GPG keys every now and then as a CRON job by populating it with keys from the different providers and removing old ones. This refresh should then also need to be activateable by a user to force refresh for a given project.

- Wharf API shall provide all GPG keys for a given project on demand for the builder to use for verifying the commits in a single endpoint. For example: `GET /projects/{projectid}/gpg/keyring` to just get all GPG keys together in PEM format (one directly after the other) so they can all be imported into GPG at once by doing:
  ```sh
  $ curl "https://wharf.local/api/projects/${PROJECT_ID}/gpg/keyring" > keyring.pub
  $ gpg --import keyring.pub
  ```
  We can later add a `GET /projects/{projectid}/gpg/keys` endpoint to receive each key with some metadata in JSON format instead, similar to [how GitLab does it](https://docs.gitlab.com/ee/api/users.html#list-all-gpg-keys). Would be nice to add just for the flexability.

- Public GPG keys will be stored in the DB. Columns needs to be
  1. (PK) incremental int
  2. (indexed) GPG key ID
  3. GPG key in PEM format (named `public_key`, `PublicKey`, or something like that)
  4. Timestamp of when it was added

  - There shall be 1:M mapping table for the project, as a key can be reused by multiple projects, and when we fetch the keys we only want keys for a given project. This comes more into effect with GitHub as you cannot simply "import ALL keys from everyone", and therefore we need to have it scoped on a per-project level, which is the lowest common denominator in this. You can figure out which providers a key exists in by looking at it's project mappings and those projects provider mappings.

---

This was originally a comment from Niklas Engvall, and I [kalle] presume it comes from his usage of Argo CD which has this feature.

**Comment by jilleJr** [comment]
Disregarding this suggestion. We think letting the forge (GitHub, GitLab, etc) be responsible for enfocing this is better. If it pops up again, we will consider it from scratch again, but removing from the backlog for now.
